### ISSUE TITLE
helm gcs fails to install on an armhf or arm64 system

### ISSUE THREAD

**Issue by andycockers** [hayorov/helm-gcs#106]
I see this with a raspberry PI 3/4.

`Installing helm-gcs 0.3.18 ...
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
helm-gcs 0.3.18 is correctly installed.

Init a new repository:
  helm gcs init gs://bucket/path

Add your repository to Helm:
  helm repo add repo-name gs://bucket/path

Push a chart to your repository:
  helm gcs push chart.tar.gz repo-name

Update Helm cache:
  helm repo update

Get your chart:
  helm fetch repo-name/chart

Installed plugin: gcs`

The plugin isn't installed, and when I try to invoke I get:

`Error: fork/exec /home/user/.local/share/helm/plugins/helm-gcs.git/bin/helm-gcs: no such file or directory
`
I can workaround it by downloading the release manually and copying the binary to the above folder.

**Comment by bilus** [comment]
I'd like to reopen this issue:

```
helm plugin install https://github.com/hayorov/helm-gcs.git
Installing helm-gcs 0.3.9 ...
tar: Error opening archive: Unrecognized archive format
helm-gcs 0.3.9 is correctly installed.
```

And then:

```
helm gcs
Error: fork/exec /Users/marcin.bilski/Library/helm/plugins/helm-gcs.git/bin/helm-gcs: no such file or directory
```

Macbook Pro, Apple M1 Pro, MacOS Ventura (v13.2)
