### ISSUE TITLE
Error: unknown flag: --service-account

### ISSUE THREAD

**Issue by hayorov** [hayorov/helm-gcs#12]
Trying to run
`helm repo update --service-account <service-account.json>`

got `Error: unknown flag: --service-account`

from help:
```
Usage:
  helm-gcs pull gs://bucket/path [flags]

Flags:
  -h, --help   help for pull

Global Flags:
      --debug                    activate debug
      --service-account string   service account to use for GCS
```

**Comment by nouney** [comment]
Hi @hayorov,

Unfortunately I'm not able to check that right now. My guess is that the flag is handled by `helm` and not forwarded to the binary `helm-gcs`.
Could you try this as a workaround?

```
$ export GOOGLE_APPLICATION_CREDENTIALS=<service-account.json>
$ helm repo update
```

**Comment by hayorov** [comment]
@nouney thank you for the quick response. 

Yes, I'm sure that issue with capturing args by an original helm handler.

The w/a with external works well.
