### ISSUE TITLE
.helm\plugins\helm-gcs\scripts\pull.sh: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by dkirrane** [hayorov/helm-gcs#13]
Hitting the following while adding repo:
```
helm repo add oceana-gcp gs://my-team-helm-repo --debug
Error: Looks like "gs://my-team-helm-repo" is not a valid chart repository or cannot be reached:
fork/exec C:\Users\me\.helm\plugins\helm-gcs\scripts\pull.sh: %1 is not a valid Win32 application.
```

```
$ ~/.helm/plugins/helm-gcs/bin/helm-gcs.exe version
version: 0.2.0
commit: 12854b9ec61b242dba21786181b9af5a4e7692c6
date: 2018-05-31T11:11:26Z
```

```
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Comment by dkirrane** [comment]
I've tried using `helm-gcs.exe` directly and here's the output

`init` is successful:
```bash
$ cd ~/.helm/plugins/helm-gcs/bin
$ ./helm-gcs.exe init gs://helmbucket/charts --debug --service-account="C:/service-account.json"
time="2018-10-16T15:44:56+01:00" level=debug msg="create a repository with index file at gs://helmbucket/charts/index.yaml"
time="2018-10-16T15:44:58+01:00" level=debug msg="push index file"
```

`pull` fails:
```bash
$ ./helm-gcs.exe pull gs://helmbucket/charts --debug --service-account="C:/service-account.json"
Error: storage: object doesn't exist
Usage:
  helm-gcs pull gs://bucket/path [flags]

Flags:
  -h, --help   help for pull

Global Flags:
      --debug                    activate debug
      --service-account string   service account to use for GCS

storage: object doesn't exist
```

I'm using GitBASH `2.16.1.windows.4` on Windows 10.
I've tried using both service account json and `gcloud auth application-default login`

**Comment by nouney** [comment]
Hi @dkirrane 

Sorry for the inconvenience, I'll look at it as soon as possible

**Comment by dkirrane** [comment]
Did you get any time to look at this?
I'll try Linux version now to see if I can workaround it for now

**Comment by nouney** [comment]
Sorry for the delay, I'm very busy and completely forgot. 

There may be a problem with the shell scripts on Windows, I need to investigate further.

In the meantime, you can use `helm-gcs.exe` but your pull command is incorrect, it should be:

`./helm-gcs.exe pull gs://helmbucket/charts/<your-chart-0.1.0.tgz> --debug --service-account="C:/service-account.json" > your-chart-0.1.0.tgz`

I know this command is not very convenient, I'm working on that.

**Comment by Klaboe** [comment]
Any updates on this? 

When you have alot of charts then the workaround becomes a little ..cumbersome ;)

**Comment by Dyhr** [comment]
I have the same issue. It kinda sucks that the plugin doesn't work on windows at all

**Comment by Klaboe** [comment]
@Dyhr : I just ended up installing it in WSL 🤷‍♂️

**Comment by Dyhr** [comment]
@Klaboe, thanks
