### ISSUE TITLE
Add option to add http(s) URLs to index.yaml

### ISSUE THREAD

**Issue by qmfrederik** [hayorov/helm-gcs#14]
I would like to use helm-gcs to publish my Helm charts, but let clients use http(s) to download the Helm charts.

Would it be possible to get a `--url` option to the `helm gcs push` command, which allows me to either add additional URLs (e.g. a HTTP or HTTPS URL for my GCS bucket), or override the default URL?

Thanks!

**Comment by hayorov** [comment]
@qmfrederik thank you for suggestion. Do you want to contribute the change?

**Comment by benjlevesque** [comment]
I submitted a PR that should resolve this issue: https://github.com/hayorov/helm-gcs/pull/23
2 options: either default public (https://[bucket-name].storage.googleapis.com) or custom url
