### ISSUE TITLE
Default public URL can cause TLS errors

### ISSUE THREAD

**Issue by koxu1996** [hayorov/helm-gcs#150]
## Context

This is the case, where _helm-gcs_ is used to store public charts (`--public` option). Because the default bucket URL `https://storage.googleapis.com/charts.yourdomain.com` is not user-friendly, it is common to set up a CNAME redirect with Cloudflare, and then the bucket can be accessed at `https://charts.yourdomain.com`. There is one requirement to make it work: the bucket must be named exactly as the domain, i.e. `charts.yourdomain.com`.

## Issue

The following code is used to generate the entry URL:

https://github.com/hayorov/helm-gcs/blob/f6d2357bbe515d38ffc3d0ed5f91275a80af7e87/pkg/repo/repo.go#L357-L361

Therefore, for a bucket with the domain name, you get a URL like: 

```
https://charts.yourdomain.com.storage.googleapis.com/Test-1.0.12.tgz
```

If you try to access it, you will get certificate error `NET::ERR_CERT_COMMON_NAME_INVALID`. That is because the certificate is valid for `*.storage.googleapis.com`, and `charts.yourdomain.com.storage.googleapis.com` is not matching it (wildcard does not work multi-level).

## Solution

Replace default public URL pattern:

```go
"https://%s.storage.googleapis.com/%s"
```

with the one that provides a bucket name as part of the query path: 

```go
"https://storage.googleapis.com/%s/%s"
```

This should work for all cases - both private and public repositories.

**Comment by hayorov** [comment]
**https://github.com/hayorov/helm-gcs/releases/tag/0.4.0**

**Comment by koxu1996** [comment]
Thanks!

**Comment by hayorov** [comment]
thanks for your contibution @koxu1996 !
