### ISSUE TITLE
gcs init fails 

### ISSUE THREAD

**Issue by prabuvenkat** [hayorov/helm-gcs#18]
I am unable to get <code>helm gcs init</code> to work. Irrespective of which auth method i use, it invariably fails with--

```
ERROR: (gcloud.auth.application-default.login) Invalid file format. 
See https://developers.google.com/api-client-library/python/guide/aaa_client_secrets 
Expected a JSON object with a single property for a "web" or "installed" application
```

I have tried these (all env variables below are configured properly) :

1. With application-default 
```
echo $GCLOUD_SERVICE_KEY > ${HOME}/account-auth-deploy.json
gcloud auth application-default login --client-id-file=${HOME}/account-auth-deploy.json
gcloud --quiet container clusters get-credentials $CLOUDSDK_CONTAINER_CLUSTER
```

2. With application default (alt)
```
gcloud auth application-default login --client-id-file=${HOME}/account-auth.json
```

3. With google app creds env var
```
export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/account-auth-deploy.json
```

Neither of these seem to have any effect.

Using: helm 2.13.1, gcs plugin latest.

**Comment by hayorov** [comment]
> ERROR: (gcloud.auth.application-default.login) Invalid file format. 

@prabuvenkat make sure that your service account credentials file is good. Check out the format and contents here https://cloud.google.com/iam/docs/creating-managing-service-account-keys

Working example (from out CI/CD pipeline):

     echo $GCLOUD_SERVICE_KEY > /gcloud-service-key.json
     gcloud auth activate-service-account --key-file=/gcloud-service-key.json

**Comment by hayorov** [comment]
@prabuvenkat may I ask you to share more details, debug output and your sanitized content of service account (json)?
