### ISSUE TITLE
Old bug happening again on 0.4.3

### ISSUE THREAD

**Issue by GuyCarmy** [hayorov/helm-gcs#189]
Error: looks like "gs://***/" is not a valid chart repository or cannot be reached: plugin "scripts/pull.sh" exited with error

It doesnt happen on 0.4.1 .

this issue happened before
https://github.com/hayorov/helm-gcs/issues/118

**Comment by abdalluhmostafa** [comment]
same issue with me

**Comment by GuyCarmy** [comment]
@hayorov fyi, assuming you are still online

**Comment by hanyhesham** [comment]
The same here:

Installing helm-gcs 0.4.3 ...
tar: Error opening archive: Unrecognized archive format
helm-gcs 0.4.3 is correctly installed.

**Comment by hornv** [comment]
yes, you have v0.4.2 in releases so it could not install it. please fix it ))

**Comment by Ibrahimkhawaja** [comment]
Same Issue on Ubuntu 22.04.2.

**Comment by PaulFederato** [comment]
I got the same issue and was able to get around by manually specifying a valid version until this gets fixed.

```
helm plugin install https://github.com/hayorov/helm-gcs.git --version 0.4.1
```

**Comment by igorrudyk** [comment]
@hayorov , please merge PR https://github.com/hayorov/helm-gcs/pull/192 to resolve the problem
