### ISSUE TITLE
Helm 3 support adoption

### ISSUE THREAD

**Issue by zen4ever** [hayorov/helm-gcs#24]
I'm trying to push image to the repository using Helm v3, I was able to successfully run helm gcs init and add repository to my list of repos. But when I'm trying to do the push I see the following

```helm gcs push build/web-application-0.1.1.tgz charts-repo                                                                                      
Error: entry: load: Couldn't load repositories file (~/Library/helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
Usage:
  helm-gcs push [chart.tar.gz] [repository] [flags]

Flags:
      --force   upload the chart even if already indexed
  -h, --help    help for push
      --retry   retry if the index changed

Global Flags:
      --debug                    activate debug
      --service-account string   service account to use for GCS

entry: load: Couldn't load repositories file (~/Library/helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
Error: plugin "gcs" exited with error```

**Comment by hd-rk** [comment]
`helm-gcs` is currently incompatible with Helm 3.0.0-beta.3 as it is using Helm 2 API (you can check the dependency). 
Recently there was a change in Helm 3 to follow XDG file directory convention, therefore if you use Helm 3, `repositories.yaml` is actually stored in a different place than where Helm 2 API is pointing to, resulting in `helm-gcs` not being able to the one find created by Helm 3 `helm` command.

I forked the repo and made a batch for this issue and have been using it for a while. However I did not have time to create proper test. You can still check it out if you want.

**Comment by hayorov** [comment]
@hd-rk it would be nice if you will have a change to create a PR with support

**Comment by hayorov** [comment]
I've started helm 3 beta support adoption.

**Comment by dibitss** [comment]
Hi @hayorov, is there any ETA on this or at least any way to workaround the issue for the time being? You mentioned a forked repo, but I couldn't find it.

**Comment by lwsanty** [comment]
@dibitss https://github.com/hd-rk/helm-gcs

**Comment by hayorov** [comment]
Thank you @lwsanty, I've adopted @hd-rk fork and switched master to helm 3. helm v2 available with `--version 0.2.2`

**Comment by glueric** [comment]
This still doesn't work on version 0.3.0.

`helm gcs push can-server-charts-repo/game-0.1.0.tgz can-server-chartsError: repo entry: load repo file: couldn't load repositories file (/Users/xxxx/Library/Preferences/helm/repositories.yaml): open /Users/xxxx/Library/Preferences/helm/repositories.yaml: no such file or directory
ls ~/.helm/repository/
cache                   local                   repositories.yaml`

**Comment by glueric** [comment]
Some more details on my problem. I was actually using Helm v2. So it looks like possibly some bug after the change you made to support helm 3, causes an issue with helm 2.

**Comment by hd-rk** [comment]
@glueric Helm 3 charts & configuration files are stored in different directories. You might consider migrating Helm 2 to 3, as discussed in https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/#migrate-helm-v2-configuration.
This plug-in uses Helm 3 to point it to the configuration files, hence the issue you encountered.

**Comment by glueric** [comment]
Yes I have since migrated to helm 3. I'm actually just using github natively now to act as my helm repository instead of using GCS. Makes the process incredibly simple. Here's the process I used: 
https://blog.softwaremill.com/hosting-helm-private-repository-from-github-ff3fa940d0b7

**Comment by hayorov** [comment]
@glueric it's a nice alternative to utilize GitHub web server for repo hosting if you with GitHub. 

Recap:
version 0.3.0+ supports **Helm 3** and there is no backward compatibility, for helm 2 version **0.2.2** has to be used.
