### ISSUE TITLE
Query: how to manage multiple repositories that exist in different GCP projects

### ISSUE THREAD

**Issue by sarmak1179** [hayorov/helm-gcs#30]
Hi,
We have setup chart repositories (buckets) in two different accounts. I am setting up the environment variable, GOOGLE_APPLICATION_CREDENTIALS to the corresponding account to push/fetch the helm charts.
But the same thing will not work with "helm repo update". Is there a way that I can supply the service account (in fact multiple service accounts) to "helm repo update" through this plugin?
Or any other suggestion?

Thanks,
Sarma K

**Comment by mehdicopter** [comment]
I woud suggest you use one service account with the proper rights on both of your buckets.

**Comment by hayorov** [comment]
> I would suggest you use one service account with the proper rights on both of your buckets.

I agree with you, it has to be the easiest way to put the plan into action.
