### ISSUE TITLE
Helm3 not detecting latest charts

### ISSUE THREAD

**Issue by drucejb** [hayorov/helm-gcs#42]
I'm using 'version: "0.3.1' version of the hayorov/helm-gcs plugin.  Using helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}.

Running "helm search repo my-gcp-helm-repo" returns:
`NAME                                                    CHART VERSION   APP VERSION     DESCRIPTION
my-gcp-helm-repo/credentials                           2.2.0+12        2.2.0           A Helm chart for deploying configmaps and secrets
`

but 2.2.0+17 exists in the bucket.  Why is that not seen as the latest version?

**Comment by hayorov** [comment]
Fixed in https://github.com/hayorov/helm-gcs/pull/44
