### ISSUE TITLE
Can't use --service-account flag with helm repo add

### ISSUE THREAD

**Issue by adkinsjd** [hayorov/helm-gcs#45]
I can't figure out how to use the service-account flag with helm repo add. Is this possible?

If it's not possible, it makes sense why it would be difficult, but it should be more clearly documented in the README.

**Comment by eyn** [comment]
To get round this you can do:


```
$> export GOOGLE_APPLICATION_CREDENTIALS=<Path to credentials file>
$> helm repo add .....
```

**Comment by adkinsjd** [comment]
Yes I'm aware, it's just poorly documented.
