### ISSUE TITLE
Whether supports helm3 dependency function in Chart.yaml

### ISSUE THREAD

**Issue by xiaofeixeniro** [hayorov/helm-gcs#46]
As the titile.
After I push the chart package to GCS,  I find the Chart.yaml of package miss the dependency for Helm 3.
Any comments?
Thanks a lot!

**Comment by hayorov** [comment]
Hello @xiaofeixeniro could you provide more details (steps to reproduce) about the issue?

**Comment by xiaofeixeniro** [comment]
This issue has been found, you can close this ticket, thanks a lot!

**Comment by hayorov** [comment]
@xiaofeixeniro nice to hear. Closing the issue.
