### ISSUE TITLE
exit code of tar not handled

### ISSUE THREAD

**Issue by pc-jedi** [hayorov/helm-gcs#47]
The following error occurred in a CI Pipeline so I cannot reproduce it, but I it happen while GitHub had issues with connections timing out.

Below some printout:
 
```
helm plugin install https://github.com/hayorov/helm-gcs
Installing helm-gcs 0.3.1 ...
tar: invalid magic
tar: short read
helm-gcs 0.3.1 is correctly installed.
...
/root/.local/share/helm/plugins/helm-gcs/scripts/pull.sh: line 3: /root/.local/share/helm/plugins/helm-gcs/bin/helm-gcs: not found
Error: looks like "gs://xxxxxxxxxxx/" is not a valid chart repository or cannot be reached: plugin "scripts/pull.sh" exited with error
```
The interesting part is `tar: invalid magic`. It looks like it coming from the following line

https://github.com/hayorov/helm-gcs/blob/master/scripts/install.sh#L43

Referenz: https://github.com/helm/helm/issues/7973

**Comment by hayorov** [comment]
Thanks, @CarsonBull for the fix.
