### ISSUE TITLE
Error: exec: "sh": executable file not found in %PATH%

### ISSUE THREAD

**Issue by TomBalt** [hayorov/helm-gcs#65]
Hi there,

When I try to run on windows 10 command: helm plugin install https://github.com/hayorov/helm-gcs.git
I get an error: Error: "exec: "sh": executable file not found in %PATH%"
Helm version: version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

**Comment by hayorov** [comment]
Hello @TomBalt ,

Windows platform supported via [cygwin](https://www.cygwin.com/cygwin-ug-net/setup-net.html).
