### ISSUE TITLE
Can't pull / install a chart after its been pushed to a bucket

### ISSUE THREAD

**Issue by minaf1** [hayorov/helm-gcs#70]
Hello.
I have used the README to successfully push a chart into a bucket.
But when I get to the `helm fetch repo-name/chart`, I get multiple different errors instead of helm retrieving the chart.
I've tried the command as above:
Error: chart "chart" matching  not found in repo-name index. (try 'helm repo update'): no chart name found
I've tried the command like this (without /chart): `helm fetch repo-name`
Error: non-absolute URLs should be in form of repo_name/path_to_chart, got repo_name
I'm not sure what to put for path_to_chart.

**Comment by jayhding** [comment]
I met same issue with version 0.3.9

**Comment by hayorov** [comment]
Hello, @jayhding may I ask you to share steps to reproduce and your environment information?
