### ISSUE TITLE
Version 0.3.9 is shown as 0.3.7

### ISSUE THREAD

**Issue by joelnoomi** [hayorov/helm-gcs#75]
The two most recent releases (v0.3.8 and v0.3.9) have not had their version reflected in `plugin.yaml`. I suspect that is the reason for the following, unexpected behavior:

    $ helm plugin install https://github.com/hayorov/helm-gcs.git --version 0.3.9
    Installing helm-gcs 0.3.7 ...

Expected behavior:

    $ helm plugin install https://github.com/hayorov/helm-gcs.git --version 0.3.9
    Installing helm-gcs 0.3.9 ...

**Comment by hayorov** [comment]
Many thanks, @joelnoomi U are right, missed the YAML plugin file version bump.

**Comment by Starefossen** [comment]
This is still the case when installing. I suggest cutting a new version with only the fix to the `plugin.yaml` file as the one in the `0.3.9` tag still says `0.3.7` https://github.com/hayorov/helm-gcs/blob/0.3.9/plugin.yaml#L2

**Comment by hayorov** [comment]
@Starefossen  you are right, I've updated tags. Probably will add some automation around version propagation in plugin fine and tags management.
