### ISSUE TITLE
helm gcs init intermittently fails with permission errors

### ISSUE THREAD

**Issue by aware74** [hayorov/helm-gcs#96]
About every third time that we call helm gcs init as part of our deploy pipeline, we receive the error message:

```
Error: googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>gke-cluster@[MASKED].iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>
Usage:
  helm-gcs init gs://bucket/path [flags]
Flags:
  -h, --help   help for init
Global Flags:
      --debug                    activate debug
      --service-account string   service account to use for GCS
googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>gke-cluster@[MASKED].iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>
Error: plugin "gcs" exited with error
```

We've made sure that the service account has the Editor and Owner IAM privileges, and we've made sure that the GCS bucket permissions allow Editors and Owners to be Storage Admins.

Is it necessary for the Go language code behind helm-gcs init to have some kind of retry mechanism?

**Comment by hayorov** [comment]
Hello @aware74 , make sure that your service account has proper access to the bucket.
you can use gsutil tool to test the access.

This link might be useful https://cloud.google.com/storage/docs/uniform-bucket-level-access

**Comment by aware74** [comment]
Thank you. We were definitely using the wrong account here, and we were able to fix the issue. 

Thank you, 
Mike

**Comment by hayorov** [comment]
Great to hear @aware74. Close the issue.
